# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='youtube_code',
            new_name='youtube_video_ID',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
