# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180217_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='logo',
            new_name='cover',
        ),
    ]
